dist: bionic
language: ruby
rvm:
 — 3.0.3
env:
  matrix:
    - API_ROOT=$API_ENDPOINT
  global:
    - RAILS_ENV=test
    - CF_USER=$DEPLOY_USERNAME
    - CF_ORG=$DEPLOY_ORG
    - CF_PASS=$DEPLOY_PASSWORD
    - CF_SPACE=$SPACE
services:
  - postgresql
addons:
  postgresql: '11'
install: bundle install --jobs=3 --retry=3
before_script:
  - sudo apt-get -qq update
script:
  - bundle exec rake db:setup
  - bundle exec rake
before_deploy:
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get -qq update
  - sudo apt-get install cf7-cli
deploy:
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s $CF_SPACE
    on:
      all_branches: true
      condition: $SPACE =~ ^(ppon-development|ppon-testing|ppon-pre-production|ppon-production)$